apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matchbox.fullname" . }}-config
  labels:
    {{- include "matchbox.labels" . | nindent 4 }}
data:
  application.yaml: |
{{ toYaml .Values.matchbox | indent 4 }}
