apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "matchbox.fullname" . }}
  labels:
    {{- include "matchbox.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "matchbox.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
